### PR TITLE
German translation (de_DE)

### PR DESCRIPTION
**Pull request by killerbees19**
<s>**DO NOT MERGE!**

There are some minor glitches and I've not tested all in-game screens yet.

I'm just opening the PR as draft now to avoid double work by multiple users.

I'll test and finish this PR in the next few days…</s>

### CODE REVIEW

**Comment by killerbees19** [comment]
I'm unsure how to translate this string at the credits screen: `Video Editing` (literally "Videobearbeitung" in German)

What's the real meaning of this category? 🤔

## Testing
I've tested my translation with v0.22.0 at my Linux Desktop (Xubuntu 20.04). I've not tested the Android version yet.

Sadly I'm unable to test it with a build from source. After selecting a vehicle the game crashes:

```
cd android/assets && java -jar .../desktop/build/libs/desktop-1.0.jar
[PwGame.logStartup] 17:03:57.022 -------------------------------------------
[PwGame.logStartup] 17:03:57.022 Pixel Wheels: version='0.22.0'
[PwGame.logStartup] 17:03:57.023 Java: vendor='Ubuntu' version='11.0.14.1'
[PwGame.logStartup] 17:03:57.023 OS: name='Linux' version='5.4.0-107-generic' arch='amd64'
[Controllers] added manager for application, 1 managers active
[PwGame.loadTranslations] 17:03:57.132 Loading translations for language 'de'
[ScreenStack.setScreen] 17:03:57.597 screen=com.agateau.pixelwheels.screens.MainMenuScreen@248e319b
[ScreenStack.setScreen] 17:03:58.686 screen=com.agateau.pixelwheels.screens.SelectGameModeScreen@2d901eb0
[PlatformUtils.init] 17:03:59.458 UI type: BUTTONS
[ScreenStack.setScreen] 17:03:59.461 screen=com.agateau.pixelwheels.screens.SelectTrackScreen@312aa7c
[ScreenStack.setScreen] 17:04:00.692 screen=com.agateau.pixelwheels.screens.SelectVehicleScreen@740fb309
[RaceScreen.<init>] 17:04:01.432 Starting race on Welcome!
[ScreenStack.setScreen] 17:04:01.505 screen=com.agateau.pixelwheels.racescreen.RaceScreen@4bd31064
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lcom.agateau.pixelwheels.racer.Racer; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lcom.agateau.pixelwheels.racer.Racer; is in unnamed module of loader 'app')
        at com.agateau.pixelwheels.racescreen.GameWorldImpl.act(GameWorldImpl.java:237)
        at com.agateau.pixelwheels.racescreen.RaceScreen.render(RaceScreen.java:199)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.agateau.pixelwheels.PwGame.render(PwGame.java:173)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at com.agateau.pixelwheels.desktop.DesktopLauncher.main(DesktopLauncher.java:45)
```

Is this a known problem at the `master` branch? Any hints how to solve this issue?

(I can open a new issue for this exception if you want.)

**Comment by agateau** [comment]
Hi Christian,

Sorry for the late reply. I am going to look at your PR today hopefully. As for your questions:

- "Video Editing" is the work done to edit the promo video you can find on https://agateau.itch.io/pixelwheels (hopefully there will be more than one at some point)

- Regarding your crash: I have seen something similar in the past when I mixed Android Studio Java compiler and my system Java compiler. In this case a `make clean` can help. The good news is you do not need to rebuild the game to test it: you can use the `PW_ASSETS_DIR` environment variable to run a prebuilt version of the game with your own assets directory. This is documented here: https://github.com/agateau/pixelwheels/blob/8fee03531303e5bc05b39c39ce22e38704593cb3/docs/translations.md#testing-a-translation. Let me know if the instructions are clear enough, I haven't had much feedback about them :)

**Comment by killerbees19** [comment]
> Sorry for the late reply.

No problem, your reaction time is fast enough. Don't worry :D

> "Video Editing" is the work done to edit the promo video you can find on https://agateau.itch.io/pixelwheels (hopefully there will be more than one at some point)

So a perfect match for "Videobearbeitung". Thanks for clarification :-)

> you can use the `PW_ASSETS_DIR` environment variable to run a prebuilt version of the game with your own assets directory.

Already done, without any problems. That's what I meant with this sentence:

> I've tested my translation with v0.22.0 at my Linux Desktop (Xubuntu 20.04).

However some buttons are not translated at v0.22.0, still displaying the English string.

I'll look into your instructions for building from source again in the next few days.

**Comment by agateau** [comment]
> > you can use the `PW_ASSETS_DIR` environment variable to run a prebuilt version of the game with your own assets directory.
> 
> Already done, without any problems. That's what I meant with this sentence:
> 
> > I've tested my translation with v0.22.0 at my Linux Desktop (Xubuntu 20.04).

Good to hear! If you still have issues building from souce, then you can use the master prebuilts from https://builds.agateau.com/pixelwheels/.

**Comment by agateau** [comment]
Looks good, merging it, thanks a lot!
Can I use the email from your commits to notify you when the translation needs to be updated?

**Comment by killerbees19** [comment]
> Can I use the email from your commits to notify you when the translation needs to be updated?

Sure! 🙂

Or just mention me somewhere in the issues or PRs with @killerbees19. (Probably slower reaction.)

Thanks again for this game 👍

**Pull request merged**
