### PR TITLE
Multiple improvements to RU translation

### PR DESCRIPTION
**Pull request by Nickoriginal**
Thanks for making more texts translatable! I have some questions about "Tiny sur Mer", "2-Deuch" and "Ant On-1" strings, that's why I am making this PR draft for now.
As far as I know, "sur Mer" means "on the sea"? In this case, what does mean "Tiny"?
I have also removed empty unnecessary quotes and I want to open a second PR to do this for all .po translations to a bit simplify them.

### CODE REVIEW

**Comment by agateau** [comment]
Those are a bit tricky because they are French references. I need to find a way to make them easier to translate 🤔.

*Tiny sur Mer*

In France, lots of cities or villages located near the sea are called "Something-sur-Mer". Pixel Wheels was originally called Tiny Wheels, before I found out the name was already used by another game. Tiny is a reference to this.

*2-Deuch*

The car with this name is inspired from a [Citroën 2CV Charleston](https://en.wikipedia.org/wiki/Citro%C3%ABn_2CV). It looks like this:
Charleston

One of the nicknames of this car is "Deudeuche" (because 2 is Deux in French), so 2-Deuch is a reference to this.

*Ant On-1*

This one is even more obscure. The first version of this bus was drawn by my son, Antonin. The bus was originally named "Antonin", but I decided to obfuscate it a bit. 1 is pronounced like the "in" at the end of Antonin. My idea with the obfuscated name is that "Ant" would be the maker name and "On-1" is the model name.

> I have also removed empty unnecessary quotes

Can you point me to where these empty unnecessary quotes are? The .po files are regularly regenerated by the `msgmerge` tool, so there is a high probability that it would put them back next time it runs.

**Comment by Nickoriginal** [comment]
Thanks!
> Can you point me to where these empty unnecessary quotes are?

For example, look [here](https://github.com/agateau/pixelwheels/blob/master/android/assets/po/messages.pot#L822), [here](https://github.com/agateau/pixelwheels/blob/master/android/assets/po/messages.pot#L657), [here](https://github.com/agateau/pixelwheels/blob/master/android/assets/po/messages.pot#L635) and [here](https://github.com/agateau/pixelwheels/blob/master/android/assets/po/messages.pot#L617) in the messages.pot.

**Comment by agateau** [comment]
> It can remove them in the existing files?

Oh, no it does not :/

> "[CPU](https://github.com/agateau/pixelwheels/blob/master/android/assets/po/messages.pot#L786)" is not translatable?

What do you mean with this? Your translation does not show up? I just changed the french word for it and it worked here.

**Comment by Nickoriginal** [comment]
> What do you mean with this?

It is present in translations, but it seems to be not translatable, as it is just a placeholder. I should keep it without changing?

**Comment by agateau** [comment]
Looks like CI is happy, merging it. Thanks for the update!

**Pull request merged**
