### PR TITLE
Multiple translations improvements

### PR DESCRIPTION
**Pull request by Nickoriginal**
Multiple formatting improvements and other improvements (REALLY big PR to follow the #233, see commit extended description for more info)

### CODE REVIEW

**Comment by agateau** [comment]
I am a bit worried the formatting changes you made won't stay this way unless translators edit their .po files with a text editor. Tools like poedit are going to reformat the file when they save. I don't want to impose a formatting style to translators. What do you think?

**Comment by Nickoriginal** [comment]
Hm, I don't use PO text editors now, because it is simpler to me to maintain my translation with plain editor. Then I will only remove the empty lines?

**Comment by Nickoriginal** [comment]
However they will not see any formatting changes in this case

**Comment by agateau** [comment]
Let's merge this, then it's up to individual translators to decide whether they prefer to keep their translation file formatted this way.

**Pull request merged**
