### PR TITLE
Esperanto translation

### PR DESCRIPTION
**Pull request by jorgesumle**

### CODE REVIEW

**Comment by agateau** [comment]
Hi, thanks for this translation! A few things are missing before it can be merged: it needs an entry in android/assets/ui/languages.xml and your name in the "Translation" section of android/assets/screens/credits.gdxui.

You can have a look at https://github.com/agateau/pixelwheels/blob/master/docs/translations.md#adding-a-new-translation to learn more.

**Comment by jorgesumle** [comment]
I've finished! Can you do the CHANGELOG stuff afterwards? There will be conflicts if I change that file.

**Comment by hendursaga** [comment]
I actually had a half-finished translation sitting on my disk. I've found some errors here, but I'm not sure how to add a commit to another's PR..

**Comment by jorgesumle** [comment]
Vi devas kloni mian deponejon kaj poste mi povas `git pull` kaj `git push` viajn ŝanĝojn

Se vi ankoraŭ ne scias, vi povas sendi al mi la korektitan dosieron kaj mi mencios vian nomon en la *commit*. Aŭ vi povas diri ĉi tie la erarojn.

**Comment by jorgesumle** [comment]
Pixel means _bildero_, [laŭ PIV](https://vortaro.net/#bildero_kd). I've corrected some errors, but the other changes aren't corrections; I think some are wrong. For instance, _Novan ĉampionadon malŝlositan!_ shouldn't be written in accusative, because it means "[a] new vehicle was unlocked!", "_nova veturilo [estis] malŝlosita!_".

**Comment by hendursaga** [comment]
OK, so you're right about not using the accusative there - this is one reason I'd like to see something like [an integration with Weblate](https://github.com/agateau/pixelwheels/issues/230). It makes it easier to comment / debate on points of translation..

I'll insist on using _rastrumo_ because [the same PIV entry](https://vortaro.net/#bildero_kd) lists it (actually, _rastrumero_) as a synonym. While it's true it's longer, it's also alliterative with _radoj_, which is why I liked it better in the first place! Vikipedio's article on [pixel art](https://eo.wikipedia.org/wiki/Rastruma_bildo) and [binary images](https://eo.wikipedia.org/wiki/Bitbildo) both use _rastruma_ to mean _pixel_ in the context of pixel art.

I'm still figuring out GitHub's interface - let me see if I can do a PR review for the rest of my suggestions..

**Comment by agateau** [comment]
Looks promising! For the ""MALFERMI PROTOKOLADAN DOSIERUJON" sentence, you can insert a `\n` to break the line in two parts.

**Comment by agateau** [comment]
Ah sorry, I just merged the Hungarian translation and this causing quite a few conflicts :/. Re-running `make po-update` should fix most of them.

Regarding the missing characters in the title font: you should be able to avoid this by modifying `languages.xml` and changing the `fontset` attribute of the Esperanto entry to `xonotic` instead of `xonotic-kwajong`.

**Comment by agateau** [comment]
I went ahead and solved the conflicts. Is it OK to merge?

**Comment by jorgesumle** [comment]
> Looks promising! For the ""MALFERMI PROTOKOLADAN DOSIERUJON" sentence, you can insert a \n to break the line in two parts.

I've done that and used the word "rastruma", like @hendursaga recommended.

It's ready to merge.

**Comment by agateau** [comment]
Thanks! Merging this when CI is happy.

**Pull request merged**
