### PR TITLE
Po:bn.po

### PR DESCRIPTION
**Pull request by Oymate**

### CODE REVIEW

**Comment by agateau** [comment]
Hi! Thank you for your translation! I am working on integrating it, but there is a font issue right now, causing texts to not appear. Version 0.21.0 is about to be released so it may be too late for your translation to be in it, but it should be in 0.22.0, unless another issue appears.

Also: do not worry about the "main / build" failure: that's something I need to fix on my side as well.

**Comment by Oymate** [comment]
Will leave this to you then, if needed 'at' me

**Comment by Oymate** [comment]
I updated one last time, please check

**Comment by Oymate** [comment]
Is it syncronized now?

**Comment by agateau** [comment]
Hi, great to see you updating your translation!

As you noticed it's now integrated, thanks for your work. It looks OK to me, but I don't speak Bengali so if something is wrong I can't tell. Can you try the builds from https://builds.agateau.com/pixelwheels and tell me if something looks odd?

One missing thing is translating the word "Bengali" in this file: https://github.com/agateau/pixelwheels/blob/266ce10acccfaa1d3f980ba9da55c5b39be2f5d6/android/assets/ui/languages.xml#L6. This is the text which appears in the language selection UI. Can you look into it!

Also, I am going to need a way to notify you when a new version is about to be released, so that you can update your translation. Do you have an email address or another way for me to contact you? You can send this information to mail@agateau.com if you prefer it to remain private.

**Comment by Oymate** [comment]
The string will be "বাংলা", I will remove the repo now, since it may ping again when it auto makes builds. You can also ping me here, for the next release.

**Comment by agateau** [comment]
OK, going to add this, thanks.

**Pull request merged**
