### PR TITLE
Update German translation (v0.23.0)

### PR DESCRIPTION
**Pull request by killerbees19**
Just a quick shot as draft. I'll update the missing vehicles in the next few days…

### CODE REVIEW

**Comment by killerbees19** [comment]
I think some vehicle names are perfect without translating them. Their meaning is clear(er) this way 😌

Some questions/comments:

* **Highway Patrol**: Literally "Autobahnpolizei", but I think the old and shorter name (Police / "Polizei") is much more common in German-speaking countries.
* **2-Deuch**: As mentioned [here](https://github.com/agateau/pixelwheels/pull/228#issuecomment-1122007096) it's a [Citroën 2CV](https://en.wikipedia.org/wiki/Citro%C3%ABn_2CV). Sounds funny, but they're known as "Ente" (Duck) in everyday language. 😆
* **Dark M**: Looks like a [Batmobile](https://en.wikipedia.org/wiki/Batmobile)? Really unsure how to translate it without using the term "Batmobil". (btw: I'm not a Batman expert/fan.)
* **Miramar**: What the hell is that? 😱

Some notes to championship and track names:

* **Country Life**: Literally "Landleben" or "Provinzleben". I'd shorten it to just "Provinz" because it sounds much better with the suffix "Meisterschaft" (Chamionship).
* **Square Mountains**: Literally "Quadratische Berge", but that sounds strange in German. I'd suggest "Gebirgsrallye" (Mountain rally) for my German translation.
* **Pix Cities**: "Pixelstädte" sounds reasonable, it's still a reference to _Pixel_ as in _Pixelwheels_.
* **River**: "Fluss" sounds a little bit lame in German. Maybe "Flussrundfahrt" (river cruise) is alright?
* **Flood**: "Flut", "Hochwasser", "Überschwemmung", … but there's a much better translation possible – "Land unter!" (Land submerged!)
* **Let it snow**: Literally "Lass es schneien" and I'm not happy with this German phrase. Is "Schneelandschaft" (snowscape) acceptable for you?
* **Don't slip**: Literally "Rutsch nicht aus". I think "Blitzeis" (black ice) sounds better and the meaning should be nearly equal.
* **Tiny sur Mer**: My first idea was "Seestadt" (seaside town). If you want a reference to the old/new game name… – hmm, maybe something like "Pix am See" could be a really nice alternative.

**Comment by agateau** [comment]
> Sorry for the delay…

No problem! (I haven't started updating the French translation yet!)
 
> I think some vehicle names are perfect without translating them. Their meaning is clear(er) this way

Yes, definitely. It is important that the names can be translated for non-latin languages, but it's not mandatory if it makes sense to use the original name. In this case, you can just copy the original, it helps when I compute stats to check translation completeness.

> Some questions/comments:
> 
>     * **Highway Patrol**: Literally "Autobahnpolizei", but I think the old and shorter name (Police / "Polizei") is much more common in German-speaking countries.

Sounds good.
 
>     * **2-Deuch**: As mentioned [here](https://github.com/agateau/pixelwheels/pull/228#issuecomment-1122007096) it's a [Citroën 2CV](https://en.wikipedia.org/wiki/Citro%C3%ABn_2CV). Sounds funny, but they're known as "Ente" (Duck) in everyday language.

Oh I didn't know the 2CV had a German nickname, that's awesome, do use it :)

>     * **Dark M**: Looks like a [Batmobile](https://en.wikipedia.org/wiki/Batmobile)? Really unsure how to translate it without using the term "Batmobil". (btw: I'm not a Batman expert/fan.)

Yes, it's inspired from the Batmobile, I didn't want to directly refer to it to avoid any legal issue (in the unlikely case that Pixel Wheels become a smash hit...) The name is a weird mix of "Dark Knight" (one of Batman nicknames) and "Mobile".

>     * **Miramar**: What the hell is that? scream

Nobody has yet found the reason why this vehicle is called this way. I don't want to spoil the mystery, but I can tell it is a place in France, so you can keep it as is.

> Some notes to championship and track names:
> 
>     * **Country Life**: Literally "Landleben" or "Provinzleben". I'd shorten it to just "Provinz" because it sounds much better with the suffix "Meisterschaft" (Chamionship).
> 
>     * **Square Mountains**: Literally "Quadratische Berge", but that sounds strange in German. I'd suggest "Gebirgsrallye" (Mountain rally) for my German translation.
> 
>     * **Pix Cities**: "Pixelstädte" sounds reasonable, it's still a reference to _Pixel_ as in _Pixelwheels_.
> 
>     * **River**: "Fluss" sounds a little bit lame in German. Maybe "Flussrundfahrt" (river cruise) is alright?
> 
>     * **Flood**: "Flut", "Hochwasser", "Überschwemmung", … but there's a much better translation possible – "Land unter!" (Land submerged!)
> 
>     * **Let it snow**: Literally "Lass es schneien" and I'm not happy with this German phrase. Is "Schneelandschaft" (snowscape) acceptable for you?
> 
>     * **Don't slip**: Literally "Rutsch nicht aus". I think "Blitzeis" (black ice) sounds better and the meaning should be nearly equal.
> 
>     * **Tiny sur Mer**: My first idea was "Seestadt" (seaside town). If you want a reference to the old/new game name… – hmm, maybe something like "Pix am See" could be a really nice alternative.

All these sound really good! Thanks for taking care, I am confident the German translation is going to be great.

**Comment by killerbees19** [comment]
Thanks, I'll test my changes in the next (😅) few days and mark this draft as "ready for review".

**Comment by killerbees19** [comment]
btw: "Square Mountains" and "Country Life" isn't translated in the GUI at `pixelwheels-0.22.0+master-20220703T174221-abede4a-linux64.zip`. Sadly I've missed that glitch, don't know why.

I'll look into this again 😩

**Pull request merged**
