### PR TITLE
New Russian translation

### LINKED ISSUE #190: New translation (RU)
Hello, Russian is my native language so I`ve prepared new Russian translation. Can I help you?

### PR DESCRIPTION
**Pull request by Nickoriginal**
Adds new Russian translation. Closes #190

### CODE REVIEW

**Comment by agateau** [comment]
Thanks, this looks promising!

screenshot-2022-01-17-232325 129
screenshot-2022-01-17-232336 683
screenshot-2022-01-17-232343 163
screenshot-2022-01-17-232346 146
screenshot-2022-01-17-232348 706

Can you confirm this looks correct?

I just added some of the required changes for the translation to work, but there is one part where i need your help: in the [android/assets/ui/languages.xml](https://github.com/Nickoriginal/pixelwheels/blob/master/android/assets/ui/languages.xml#L6) file, the `Russian` in `name="Russian"` must be in Russian itself. Can you make the change?

Also, as you can see, some texts are a bit too long,  is it possible to use shorter sentences? If not I can look into reducing the font size for Russian.

**Comment by Nickoriginal** [comment]
> Can you confirm this looks correct?

Yes, it does! Although some strings "Открыть папку с файлом лога" and "Посетить страницу поддержки" are overlapping, I don't think, that it is translation issue.

> Also, as you can see, some texts are a bit too long, is it possible to use shorter sentences?

Okay, I will try now.

**Comment by Nickoriginal** [comment]
Now shouldn't be overlapping.

**Comment by agateau** [comment]
Yes, that looks good!

screenshot-2022-01-18-225704 240
screenshot-2022-01-18-225705 909

Thanks a lot, merging your work in!

**Comment by agateau** [comment]
One more thing: I am going to need a way to let you know when the translation needs to be updated in the future. Can you send me your email address at mail@agateau.com?

**Comment by Nickoriginal** [comment]
Thank you for using my translation!
> Can you send me your email address at mail@agateau.com?

Yes, of course!

**Pull request merged**
