### PR TITLE
heading-up-mode

### PR DESCRIPTION
**Pull request by complyue**
I'm not a game dev myself, just came to this game by accident and enjoyed it.

But currently as "retro" as it is, the driving experience feels more like controlling a RC car model. I think I would enjoy more in more realistic feeling of heading up mode, then tinkered with the code base, and come with a basic hack of the desired feel.

Current changes are way very basic and lack a lot of adjustments to get it all right, yet it's only 3 lines changed atm.

I'd like to know what you think about this mode before any proceeding, and definitely need your help and efforts to get it all done.

A few of my thoughts what can/shall be done:

1. make it an option to race in this mode, maybe better along with portrait display mode of the phone
2. proper camera handling when the car is moving back
3. fix clipping for the camera
4. further tune the physics for driving experience

WRT 4, I'd suggest that the acceleration should be greatly slowed down (I drive comfortably only with force 30 instead of the default 50), maybe add shifting of a real car and physics / sounds for the engine to work at respective RPMs. Also physics to slow down the turning to make the feel more apparent, i.e. the camera heads up the car's real moving direction, when the car turns, the gamer should see the car body tilts for a moment before the drifting force pushed the car's velocity to the desired direction, drifting or not should have different physical models.

Hope you find this idea approachable & worth trying.

### CODE REVIEW

**Comment by agateau** [comment]
Hi @complyue, sorry for the late reply, going to look at your work.

**Comment by agateau** [comment]
A bit of history might be interesting here :)

This camera behavior used to exist in Pixel Wheels. It was the default behavior with an option to disable it until 0.10.0. In 0.10.0 the fixed camera became the default behavior. The option was then removed in 0.12.0 because at that time I modified the multi-player mode so that all players shared the same screen. In this situation it made no sense to have a rotating camera. Then in 0.25.0 multi-player mode was changed back to use a split-screen again, so a rotating camera behavior option makes more sense again.

I enjoyed the rotating camera, but when showing the game to others people they were always confused and complained it rotated too fast. Quoting the 0.10.0 changelog:

> Camera does not rotate to follow the player vehicle anymore by default. As much as I like this feature, almost every player prefers when the camera does not rotate, so let's change the default.

Maybe the problem was not the camera but the fact that (as you pointed out) the vehicles drive probably too fast right now.

I would be very happy to bring this behavior back, but there are a few challenges. I tried your branch: right now the camera rotation is quite brutal, but as you said, it's a bit of a hack (I am impressed by how little changes you needed to get to this result!). This can be fixed, but the trickier challenge is empty borders. This was not working really well in the original implementation either: when the vehicle is near the border of the map, often the rotated camera would show the empty space outside the map. This was mitigated a bit by defining an empty color, but that does not work for city maps.

**Comment by complyue** [comment]
I found that I can slow down the speeding by either decreasing driveforce or increasing vehicledensity, but failed to figure out how to slow down the turning, i.e. the vehicle body's velocity seems to align with the direction it points to immediately, while I'd like to feel the steering torque to take some time in changing the direction of velocity vector. Can you give me some clue in achieving that?

**Comment by complyue** [comment]
@agateau I implemented another method with smoothed camera turning feeling, together with the gameplay params updated to what I'd like. Pls try this latest code update and see the new feel, do you like it or not?

I don't mean this PR should be merged, just hope you can add a similar mode to the official release sooner than later.

**Comment by complyue** [comment]
Sure, I'll draft separate PRs meant to be reviewed & merged as the goal, maybe for individual tweaks I can think of:

* non-linear steering control experience
* car density & drive force tuned for different feel
* other physics for different driving experience

Let's use this PR only for discussion, pls don't take the code changes here very seriously, I expected this PR ultimately closed without merged.

Wrt the heading-up camera, a serious defect to tackle is clipping of map/stuff out of the view of the non-rotating camera. I tried but always fail to make it do no such clipping. Can you please point me to the right direction to correct the rendering?

I'm going to try current hack on my phone, but I feel it beforehand that it'll be uncomfortable to play in landscape aspect ratio (which seems the only display mode so far?), as there'll be too short-sight of the road ahead. Would you plan to add portrait mode support upstream? I'll be very happy to work out the rotating-camera mod based on portrait display mode. I'd prefer manual switching option rather than gyro based auto rotation for this feature, if that matters.

Also, I'd like to know your intention, for whether rotating-camera mode, if one day accepted, should replace current fixed-camera mode, or there should be 2 user selectable modes with an added option?

**Comment by complyue** [comment]
@agateau by some luck, seems I have tackled all the defeats so far, and I think it's pretty playable with current code changes. I've removed irrelevant changes and squashed the commit history for this PR, it's solely about the rotating-camera / heading-up mode now.

Please review this PR and consider for merging, now I suggest this PR get merged, thanks!

**Comment by agateau** [comment]
> @agateau by some luck, seems I have tackled all the defects so far, and I think it's pretty playable with current code changes. I've removed irrelevant changes and squashed the commit history for this PR, it's solely about the rotating-camera / heading-up mode now.
> 
> Please review this PR and consider for merging, now I would like this PR get merged, thanks!

Hi @complyue: thanks again for this work!

I want to merge it, but I don't think heading-up should be the only and default behavior. Can you add a boolean to `GameConfig` to make it possible to toggle this behavior? I can take care of adding the necessary UI in the settings to toggle the option if you don't want to dive into PixelWheels home-made menu system :)

> I'd want the car is always centered horizontally in heading-up camera mode. I think this is relevant to the issue you mentioned in a previous reply that how to display areas out of the map region.

I agree, it makes more sense for the car to always be centered in this mode.

> May I suggest "deep space with blinking stars" for that part?

Sorry, but I don't like that idea: I think it would break the player immersion. I want to look into defining infinitely wrapping borders for maps so that the outside areas can be filled. It's not a blocker to merge the heading-up camera mode though: as long as it's not on by default, the option can be marked as "experimental" until we have a solution to fill the outside.

One last thing: I triggered the CI and it reported two issues:
- the coding style check is not happy :sweat_smile:. You can fix this with `make codingstyle-apply`.
- there is no changelog fragment: you can either add it yourself using [changie](https://github.com/miniscruff/changie), or I can do it for you and mark the PR as not requiring a changelog.

**Comment by agateau** [comment]
Just made a few minor changes and added the UI. The config screen feels a bit packed, but I can fix this later, let's merge this. Thanks a lot for your work!

image

**Comment by agateau** [comment]
> btw, as a native Chinese, I can contribute for Chinese translations too, feel free to assign me such tasks. I've noticed the big-wheeled monster truck is translated to "面包车" for now, but that's not ideal as "面包车" usually means a van instead, that's a minor issue, tho better to communicate with the original translator if possible to have it changed to "大脚卡车" or so.

This is a topic where I trust you :) I suggest you file a PR and ping @xlucn on it for review. Then I'd happily merge it.

**Comment by xlucn** [comment]
Sorry about my sloppy translations of those car names, since I am really unfamiliar with almost any vehicles.

@complyue If you know anything about them, then you are already better than me at this and feel free to correct them :)

**Comment by complyue** [comment]
@xlucn thanks, I'll submit translation PRs after familiarized myself with Changie, pls review them then.

@agateau I noticed the `make po-compile` target does not exist as the doc says, when trying to add a touch-wheel input handler, which includes some new  `tr()` calls, then the translation seems not working after built, somewhere says the `.po` files need to be compiled into `.java`, how to do that nowadays?

btw, how to add an icon for the new handler into `input-icons.ase`? can it be done without Aseprite? maybe put a plain `.png` there and update the make targets somehow?

**Comment by agateau** [comment]
> I noticed the make po-compile target does not exist as the doc says, when trying to add a touch-wheel input handler, which includes some new tr() calls, then the translation seems not working after built, somewhere says the .po files need to be compiled into .java, how to do that nowadays?

Ah right, that target no longer exists: Pixel Wheels can now directly read .po files.

> btw, how to add an icon for the new handler into input-icons.ase? can it be done without Aseprite? maybe put a plain .png there and update the make targets somehow?

No, the files have to be .ase files. If you don't have Aseprite, you should be able to use [LibreSprite](https://libresprite.github.io/) (but I haven't checked).

**Pull request merged**
